import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronRight, Download, Headphones, Moon, MoreHorizontal, Pause, Play, RotateCcw, RotateCw, Settings2, Timer, X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { useReader } from '../../context/ReaderContext';
import { BookCover } from '../common/BookCover';
import { getVoicePresentation } from '../../audio-engine/voicePresentation';

const FALLBACK_VOICES = [
  ['ngochuyen', 48.5], ['ngochuyennew', 48.5], ['maiphuong', 44], ['minhkhang', 46.2],
  ['manhdung', 46.5], ['minhthu', 44.8], ['vietthao3886', 47],
].map(([id, size]) => ({ id: String(id), ...getVoicePresentation(String(id)), modelSizeMB: Number(size), isInstalled: false, engineType: 'nghi-tts' as const }));

export const AudioPlayerSheet: React.FC = () => {
  const { currentBook, canUseFeature } = useApp();
  const { isAudioSheetOpen, setIsAudioSheetOpen, audioState, audioAccess, availableVoices, togglePlayAudio, seekAudio, setAudioSpeed, setAudioVoice, setAudioSleepTimer, setAudioAutoNext, setAudioReadTitle, skip15Sec, currentChapterIndex, currentChapterTitle, downloadVoiceModel } = useReader();
  const [panel, setPanel] = useState<'player' | 'voices' | 'settings'>('player');
  const [speedOpen, setSpeedOpen] = useState(false);
  const [timerOpen, setTimerOpen] = useState(false);
  const voices = useMemo(() => {
    const neural = availableVoices.filter(v => v.engineType !== 'system-speech');
    return neural.length ? neural : FALLBACK_VOICES as any[];
  }, [availableVoices]);
  const deviceVoices = availableVoices.filter(v => v.engineType === 'system-speech');
  const activeVoice = [...voices, ...deviceVoices].find(v => v.id === audioState.voice);
  const voiceCopy = getVoicePresentation(audioState.voice, activeVoice);
  const entitled = canUseFeature('audio') || audioAccess.enabled;
  const progress = Math.max(0, Math.min(100, audioState.chunkProgressPercent));
  if (!isAudioSheetOpen) return null;

  if (!entitled) return null;

  const close = () => { setPanel('player'); setIsAudioSheetOpen(false); };
  return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-ink-950/35 backdrop-blur-sm sm:p-5 animate-in fade-in duration-150">
    <div className="relative w-full sm:max-w-md h-[100dvh] sm:h-auto sm:max-h-[92vh] overflow-y-auto bg-[#fbf7f1] sm:rounded-[32px] shadow-modal animate-in slide-in-from-bottom duration-200">
      {panel === 'player' && <div className="min-h-full px-5 pt-[max(1rem,env(safe-area-inset-top))] pb-[max(1.5rem,env(safe-area-inset-bottom))] sm:p-6">
        <header className="flex items-center justify-between h-11"><button onClick={close} className="p-2 rounded-full hover:bg-white text-ink-600"><X className="w-5 h-5" /></button><span className="text-sm font-semibold text-ink-800">Nghe truyện</span><button onClick={() => setPanel('settings')} className="p-2 rounded-full hover:bg-white text-ink-600"><MoreHorizontal className="w-5 h-5" /></button></header>
        <div className="relative mt-3 flex justify-center"><div className="absolute inset-x-16 inset-y-5 rounded-full bg-lily-300/20 blur-3xl" /><div className="relative drop-shadow-[0_20px_25px_rgba(62,37,31,.22)]"><BookCover title={currentBook?.title || 'Truyện'} author={currentBook?.author} coverUrl={currentBook?.coverUrl} coverColor={currentBook?.coverColor} format={currentBook?.fileFormat} size="lg" /></div></div>
        <div className="mt-5 text-center px-4"><h2 className="font-serif text-xl font-semibold text-ink-950 truncate">{currentBook?.title || 'Truyện của bạn'}</h2><p className="mt-1 text-sm text-ink-500 truncate">{currentChapterTitle || `Chương ${currentChapterIndex}`}</p></div>
        <div className="mt-6"><input type="range" min="0" max={Math.max(0, audioState.totalChunks - 1)} value={audioState.currentChunkIndex} onChange={e => seekAudio(Number(e.target.value))} className="w-full h-1 accent-lily-700 cursor-pointer" aria-label="Tiến độ nghe" /><div className="mt-1.5 flex justify-between text-[11px] text-ink-400"><span>Chương {currentChapterIndex}</span><span>{progress}%</span></div></div>
        <div className="mt-5 flex items-center justify-center gap-8"><button onClick={() => skip15Sec('backward')} disabled={audioState.currentChunkIndex <= 0} className="p-3 text-ink-600 disabled:opacity-30" aria-label="Phần trước"><RotateCcw className="w-5 h-5" /></button><button onClick={togglePlayAudio} className="w-16 h-16 rounded-full bg-gradient-to-br from-lily-600 to-lily-800 text-white flex items-center justify-center shadow-[0_14px_32px_-12px_rgba(125,41,73,.65)] active:scale-95 transition-transform">{audioState.status === 'SYNTHESIZING' ? <span className="w-5 h-5 rounded-full border-2 border-white/40 border-t-white animate-spin" /> : audioState.isPlaying ? <Pause className="w-6 h-6 fill-white" /> : <Play className="w-6 h-6 fill-white ml-1" />}</button><button onClick={() => skip15Sec('forward')} disabled={audioState.currentChunkIndex >= audioState.totalChunks - 1} className="p-3 text-ink-600 disabled:opacity-30" aria-label="Phần tiếp theo"><RotateCw className="w-5 h-5" /></button></div>
        {audioState.status === 'SYNTHESIZING' && <p className="mt-2 text-center text-xs text-ink-400">Đang chuẩn bị giọng Lily…</p>}
        <div className="mt-6 divide-y divide-ink-100 border-y border-ink-100"><button onClick={() => setPanel('voices')} className="w-full py-3 flex items-center justify-between text-sm"><span className="text-ink-500">Giọng đọc</span><span className="flex items-center gap-2 font-medium text-ink-900">{voiceCopy.name}<ChevronRight className="w-4 h-4 text-ink-300" /></span></button><div className="grid grid-cols-2 divide-x divide-ink-100"><button onClick={() => setSpeedOpen(v => !v)} className="py-3 text-sm flex items-center justify-center gap-2"><Settings2 className="w-4 h-4 text-ink-400" />{audioState.playbackRate.toFixed(1)}×</button><button onClick={() => setTimerOpen(v => !v)} className="py-3 text-sm flex items-center justify-center gap-2"><Moon className="w-4 h-4 text-ink-400" />{audioState.sleepTimer ? `${audioState.sleepTimer} phút` : 'Hẹn giờ'}</button></div></div>
        {speedOpen && <div className="mt-3 flex justify-center gap-1.5">{[0.8,1,1.2,1.5,2].map(r => <button key={r} onClick={() => { setAudioSpeed(r); setSpeedOpen(false); }} className={`px-3 py-2 rounded-xl text-xs ${audioState.playbackRate === r ? 'bg-ink-900 text-white' : 'bg-white text-ink-600 border border-ink-100'}`}>{r.toFixed(1)}×</button>)}</div>}
        {timerOpen && <div className="mt-3 grid grid-cols-4 gap-1.5">{[10,20,30,60].map(m => <button key={m} onClick={() => { setAudioSleepTimer(m); setTimerOpen(false); }} className="py-2 rounded-xl bg-white border border-ink-100 text-xs text-ink-600">{m}p</button>)}</div>}
      </div>}
      {panel === 'voices' && <div className="min-h-full p-5 pt-[max(1rem,env(safe-area-inset-top))] pb-[max(1.5rem,env(safe-area-inset-bottom))]"><header className="flex items-center gap-3 h-11"><button onClick={() => setPanel('player')} className="p-2 rounded-full hover:bg-white"><ArrowLeft className="w-5 h-5" /></button><h2 className="font-serif text-lg font-semibold">Chọn giọng Lily</h2></header><div className="mt-4 space-y-2">{voices.map(voice => { const selected = audioState.voice === voice.id; const copy = getVoicePresentation(voice.id, voice); return <button key={voice.id} onClick={() => { if (voice.isInstalled) { setAudioVoice(voice.id); setPanel('player'); } }} className={`w-full p-3.5 rounded-2xl border flex items-center gap-3 text-left ${selected ? 'border-lily-400 bg-lily-50' : 'border-ink-100 bg-white/70'}`}><span className={`w-5 h-5 rounded-full border flex items-center justify-center shrink-0 ${selected ? 'border-lily-600 bg-lily-600 text-white' : 'border-ink-200'}`}>{selected && <Check className="w-3 h-3" />}</span><span className="min-w-0 flex-1"><strong className="block text-sm text-ink-900">{copy.name}</strong><small className="block mt-0.5 text-xs text-ink-400">{copy.description}</small></span>{voice.isInstalled ? <span className="text-[10px] text-emerald-700">Đã sẵn sàng</span> : <span onClick={e => { e.stopPropagation(); downloadVoiceModel(voice.id); }} className="px-2.5 py-1.5 rounded-xl bg-lily-100 text-lily-800 text-[10px] font-semibold flex items-center gap-1"><Download className="w-3 h-3" />Tải giọng</span>}</button>; })}</div>{deviceVoices.length > 0 && <div className="mt-6"><h3 className="text-xs font-semibold uppercase tracking-wider text-ink-400">Các giọng khác</h3><button onClick={() => { setAudioVoice(deviceVoices[0].id); setPanel('player'); }} className="mt-2 w-full p-3.5 rounded-2xl bg-white/70 border border-ink-100 text-left"><strong className="text-sm">Giọng thiết bị</strong><span className="block text-xs text-ink-400 mt-0.5">Có sẵn trên thiết bị này</span></button></div>}<p className="mt-5 text-center text-[11px] text-ink-400">Mỗi giọng chỉ cần tải một lần và có thể dùng khi offline.</p></div>}
      {panel === 'settings' && <div className="min-h-full p-5 pt-[max(1rem,env(safe-area-inset-top))] pb-[max(1.5rem,env(safe-area-inset-bottom))]"><header className="flex items-center gap-3 h-11"><button onClick={() => setPanel('player')} className="p-2 rounded-full hover:bg-white"><ArrowLeft className="w-5 h-5" /></button><h2 className="font-serif text-lg font-semibold">Cài đặt nghe</h2></header><div className="mt-4 divide-y divide-ink-100 rounded-2xl bg-white/70 border border-ink-100 px-4"><label className="py-4 flex items-center justify-between text-sm"><span>Đọc tên chương</span><input type="checkbox" checked={audioState.readChapterTitle} onChange={e => setAudioReadTitle(e.target.checked)} className="accent-lily-700 w-4 h-4" /></label><label className="py-4 flex items-center justify-between text-sm"><span>Tự phát chương tiếp theo</span><input type="checkbox" checked={audioState.autoNextChapter} onChange={e => setAudioAutoNext(e.target.checked)} className="accent-lily-700 w-4 h-4" /></label></div><div className="mt-4 p-4 rounded-2xl bg-cream-100/70 text-xs text-ink-500 flex gap-2"><Timer className="w-4 h-4 shrink-0" /><p>Nội dung truyện và giọng đọc được lưu trên thiết bị của bạn.</p></div></div>}
    </div>
  </div>;
};
